# mkdocs.yml
site_name: D2B Pipeline
site_url: https://anice1.github.io/d2b-docs/
site_description: D2b is a simple data pipeline designed to help automate the processes involved in extracting, transforming, analysing and exporting data insights carried out by data professionals at powerpedia (Imaginary Company).

repo_url: https://github.com/anice1/d2b/
repo_name: anice1/d2b

theme:
  name: material
  logo: https://img.freepik.com/premium-vector/minimal-letter-p-pipe-setting-logo_643908-269.jpg
  favicon: https://img.freepik.com/premium-vector/minimal-letter-p-pipe-setting-logo_643908-269.jpg
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

edit_uri: ""

nav:
  - ğŸ  &nbsp; Home: 'index.md'
  - ğŸ”‘ &nbsp; Handlers: handlers
  - âœ… &nbsp; Service Providers: providers
  - ğŸ“ &nbsp; Recommendations: recommendations
  
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AcNice_
    - icon: fontawesome/brands/github
      link: https://github.com/anice1/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/chimaobi.nice